name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    needs: build
    uses: ./.github/workflows/test.yml
    secrets: inherit
  cleanup:
    if: always()
    needs: build
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
