on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set License
      shell: pwsh
      run: Set-Content -Path src\PersonalRecord.App\SyncfusionLicense.txt -Value ${{ secrets.SYNCFUSION_LICENSE }} -NoNewline -Force
    - name: Restore dependencies
      run: dotnet restore ${{ vars.APP_PROJECT }} 
    - name: Restore keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        filename: ${{ secrets.KEYSTORE_FILENAME }}
        filedir: ${{ runner.temp }}
        encodedString: ${{ secrets.KEYSTORE_BASE64 }}
    - name: Publish MAUI Android AAB
      run: dotnet publish ${{ vars.APP_PROJECT }} -c ${{ vars.BUILD_CONFIGURATION }} -f ${{ vars.TARGET_FRAMEWORK }} /p:AndroidPackageFormats=aab /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=${{ runner.temp }}\${{ secrets.KEYSTORE_FILENAME }} /p:AndroidSigningKeyAlias=${{ secrets.KEYSTORE_ALIAS }} /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" --no-restore
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ vars.PACKAGE_NAME }}-Signed.aab
        path: ${{ github.workspace }}\src\${{ vars.APP_NAME }}\bin\${{ vars.BUILD_CONFIGURATION }}\${{ vars.TARGET_FRAMEWORK }}\publish\${{ vars.PACKAGE_NAME }}-Signed.aab
