on:
  workflow_call:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Integration Tests
      run: dotnet test ${{ vars.TEST_PROJECTS }}
