name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  build:
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit
  upload:
    needs: build
    uses: ./.github/workflows/upload.yml
    secrets: inherit
  cleanup:
    if: always()
    needs: upload
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
