on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ vars.AAB_NAME }}
        path: /tmp
    - name: Check file
      shell: pwsh
      run: |
        Test-Path "/tmp/${{ vars.AAB_NAME }}"
    - uses: r0adkll/upload-google-play@v1
      name: Upload to Play Console
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
        packageName: ${{ vars.PACKAGE_NAME }}
        releaseFiles: "/tmp/${{ vars.AAB_NAME }}"
        whatsNewDirectory: ${{ vars.WHATS_NEW_DIRECTORY }}
        track: internal
        status: draft
