on:
  workflow_call:

env:
  PACKAGE_NAME: com.ramo.personalrecord
  AAB_NAME: com.ramo.personalrecord-Signed.aab

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.AAB_NAME }}
        path: /tmp
    - name: Check file
      shell: pwsh
      run: |
        Test-Path "/tmp/${{ env.AAB_NAME }}"
    - uses: r0adkll/upload-google-play@v1
      name: Upload to Play Console
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
        packageName: ${{ env.PACKAGE_NAME }}
        releaseFiles: "/tmp/${{ env.AAB_NAME }}"
        track: internal
        status: draft
